fill missed benchmark data
Google Finance price data for SPY missing some dates.
This causes algo breakages like this:
    KeyError: 'the label [2012-02-02 00:00:00+00:00] is not in the [index]'

Used session data from NYSE calendar to fill missing SPY price data.

Signed-off-by: Ed Bartosh <bartosh@gmail.com>